### ISSUE TITLE
location.street2 is not being set

### ISSUE THREAD

**Issue by deepthawtz** [russ/smarty_streets#6]
Hey guys,

In `lib/smarty_streets/request.rb` the `handle_response` method seems to be ignoring `delivery_line_2` and not setting `street2`. Wondering if that's just something that was missed or..... ?

**Comment by russ** [comment]
Most likely just missed. I will look at this tomorrow. Thanks for the heads up.

**Comment by deepthawtz** [comment]
cool. thanks. Happened to notice one of our automated tests failed when we updated our gem.

**Comment by russ** [comment]
I had a chance to look at this. It's all fixed up now. New version is 0.0.5.
